name: Github Pages
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        ref: refs/heads/master
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: npm install, build and deploy
      env:
        NODE_DEBUG: gh-pages
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "GITHUB_TOKEN $GITHUB_TOKEN"
        echo "GITHUB_WORKFLOW $GITHUB_WORKFLOW"
        echo "GITHUB_ACTION $GITHUB_ACTION"
        echo "GITHUB_ACTOR $GITHUB_ACTOR"
        echo "GITHUB_REPOSITORY $GITHUB_REPOSITORY"
        echo "GITHUB_EVENT_NAME $GITHUB_EVENT_NAME"
        echo "GITHUB_SHA $GITHUB_SHA"
        echo "GITHUB_REF $GITHUB_REF"
        echo "GITHUB_HEAD_REF $GITHUB_HEAD_REF"
        echo "GITHUB_BASE_REF $GITHUB_BASE_REF"

        # curl --request POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" --url "https://api.github.com/repos/$GITHUB_REPOSITORY/pages/builds"
        # npm install
        # npm run build --if-present
        # git config --global user.email "support+actions@github.com"
        # git config --global user.name "github-actions-bot"
        # echo "GH_PAGES $GH_PAGES"
        # npm run deploy -- --user "github-actions-bot <support+actions@github.com>"


