name: Github Pages
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        ref: refs/heads/master
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: npm install, build and deploy
      env:
        NODE_DEBUG: gh-pages
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      run: |
        # curl --request POST -H 'authorization: token ${ACCESS_TOKEN}' -H 'content-type: application/json' --url https://api.github.com/authorizations
        npm install
        npm run build --if-present
        echo "---\npermalink: /index.html\n---" > dist/readme.md
        npm run deploy -- --repo "https://git:${ACCESS_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" --user "Github Actions Bot <support+actions@github.com>"

