name: Github Pages
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        ref: refs/heads/master
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: npm install, build and deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NODE_DEBUG: gh-pages
      run: |
        npm install
        npm run build --if-present
        npm run deploy

