name: Github Pages
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        ref: refs/heads/master
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: npm install, build, and deploy
      run: |
        npm install
        npm run build --if-present
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        npm run deploy

