name: Github Pages
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        ref: refs/heads/master
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: npm install, build and deploy
      env:
        NODE_DEBUG: gh-pages
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "-----------"
        echo -n "${GITHUB_TOKEN}" | wc -c
        echo "-----------"
        npm install
        npm run build --if-present
        npm run deploy -- --user "github-actions-bot <support+actions@github.com>"
        curl --silent --request POST -H "Accept: application/vnd.github.mister-fantastic-preview+json" -H "Authorization: token ${GITHUB_TOKEN}" --url "https://api.github.com/repos/${GITHUB_REPOSITORY}/pages/builds"

